BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        Button:
            text: 'Clear'
            on_press: app.clear_fields
        TextInput:
            id: input1
            font_size: 20
    BoxLayout:
        Button:
            text: 'Greet'
            on_press: app.handle_greet()
        Label:
            id: label1
            text: 'Enter your name'
            color: (1, 1, 0, 1)